config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                 
                  path("", include("csi_localhost.user_profile.urls", namespace="user_profile")),
                  path("", include("csi_localhost.game.urls", namespace="game")),
                  # Django Admin, use {% url 'admin:index' %}
                  path(r'nested_admin/', include('nested_admin.urls')),
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("csi_localhost.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

csi_localhost/game/urls.py
from django.urls import path

from .views import (
    question_view
)

app_name = "game"
urlpatterns = [
    path("next/", view=question_view, name="quiz"),
]

csi_localhost/user_profile/urls.py
from django.urls import path

from .views import (
    profile_view
    ,leader_view
    ,logout
)

app_name = "user_profile"
urlpatterns = [
    path("profile/", view=profile_view, name="redirect"),
    path("logout/", view=logout, name="logout"),
    path("leaderboard/", view=leader_view, name="lead"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
]

csi_localhost/users/urls.py
from django.urls import path

from csi_localhost.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

csi_localhost/game/models.py
import datetime

from django.db import models
from django.utils.text import slugify


# Create your models here.
class Question(models.Model):
    upload_to = 'question/'
    question = models.CharField(max_length=500)
    number = models.PositiveSmallIntegerField(unique=True)
    slug = models.SlugField(editable=False, unique=True)
    marks = models.IntegerField()
    image = models.ImageField(upload_to=upload_to)
    answer = models.CharField(max_length=100)
    is_active = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.question + str(datetime.datetime.now()))
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.question


class Meme(models.Model):
    CHOICE = ((1, "Success"), (2, "Fail"), (3, "Patience"), (4, "Congratulations"))
    category = models.PositiveSmallIntegerField(choices=CHOICE, default=1)
    content = models.CharField(max_length=200)

    def __str__(self):
        return self.content

csi_localhost/response/models.py
from django.db import models

from csi_localhost.game.models import Question
from csi_localhost.user_profile.models import Profile


class Response(models.Model):
    CHOICES = ((1, "Correct Answer"), (0, "Wrong Answer"))
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=100)
    create_date = models.DateTimeField()
    status = models.PositiveSmallIntegerField(choices=CHOICES, default=1)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

csi_localhost/rules/models.py
from django.db import models


class Rules(models.Model):
    priority = models.PositiveSmallIntegerField(unique=True)
    rule = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.priority)

    def save(self, *args, **kwargs):
        # self.rule = unescape(self.rule)
        super(Rules, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Rules'
        verbose_name = 'Rule'

csi_localhost/user_profile/models.py
from django.conf import settings
from django.db import models

from ..game.models import Question


class Profile(models.Model):
    name = models.CharField(max_length=100)
    nick_name = models.CharField(max_length=100)
    contact = models.CharField(max_length=15)
    college = models.CharField(max_length=100)
    marks = models.PositiveSmallIntegerField(default=0, blank=True, null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    has_completed = models.BooleanField(default=False)
    last_submission = models.DateTimeField()
    current_question = models.ForeignKey(Question, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Profile"

csi_localhost/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for CSI-LOCALHOST."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

csi_localhost/game/forms.py
from django import forms


class AnswerForm(forms.Form):
    answer = forms.CharField(max_length=1000)

    def clean(self):
        cleaned_data = super(AnswerForm, self).clean()
        answer = cleaned_data.get('answer')
        if not answer:
            raise forms.ValidationError('You have to write something!')

csi_localhost/user_profile/forms.py
from django.forms import ModelForm

from .models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'nick_name', 'contact', 'college']

csi_localhost/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

csi_localhost/game/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect

from csi_localhost.response.models import Response
from .forms import AnswerForm
from .models import Question, Meme
from ..user_profile import models


# Create your views here.
def question_view(request):
    if request.user.is_authenticated:
        try:
            profile = request.user.profile
        except models.Profile.DoesNotExist:

            return redirect('user_profile:redirect')

        context = {'completed': False}
        if request.method == 'POST':
            form = AnswerForm(request.POST)

            if form.is_valid():
                answer = form.data.get('answer')
                response = Response(user=profile, question=profile.current_question, answer=answer,
                                    create_date=datetime.datetime.now())
                profile.last_submission = datetime.datetime.now()
                if answer and answer == profile.current_question.answer:
                    response.status = 1
                    response.save()
                    message = Meme.objects.filter(category=1).order_by('?').first()
                    context['result'] = dict(title=answer, message=message, indicator=1, color="green")
                    number = profile.current_question.number + 1
                    profile.marks = profile.marks + profile.current_question.marks

                    if number > len(Question.objects.all()):
                        profile.has_completed = True
                        profile.save()
                        context['completed'] = True
                        return render(request, 'game/result.html', context)

                    else:
                        profile.current_question = Question.objects.get(number=number)
                        profile.save()
                        return render(request, 'game/result.html', context)

                else:
                    response.status = 0
                    response.save()
                    profile.save()
                    message = Meme.objects.filter(category=2).order_by('?').first()
                    context['result'] = dict(title=answer, message=message, indicator=0, color="red")
                    return render(request, 'game/result.html', context)

            else:
                context['form'] = form
                return render(request, 'game/question.html', context)

        elif request.method == "GET":

            if profile.has_completed:
                message = Meme.objects.filter(category=4).order_by('?').first()
                return render(request, 'game/end.html', {"flag": 1, "message": message})

            if profile.current_question is None:
                queryset = get_object_or_404(Question, number=1)
                profile.current_question = queryset
                profile.save()

            if profile.current_question.is_active:
                context['question'] = profile.current_question
                context['form'] = AnswerForm()
                return render(request, 'game/question.html', context)
            else:
                message = Meme.objects.filter(category=3).order_by('?').first()
                return render(request, 'game/end.html', {"flag": 0, "message": message})

csi_localhost/response/views.py
from django.shortcuts import render

# Create your views here.

csi_localhost/rules/views.py
from django.shortcuts import render

csi_localhost/user_profile/views.py
from django.contrib.auth import logout as log_me_out
from django.shortcuts import render, redirect
from csi_localhost.rules.models import Rules
from .forms import ProfileForm
from .models import Profile


# Create your views here.
def profile_view(request):
    user = request.user
    rules = Rules.objects.all().order_by('priority')
    if user.is_authenticated:
        if request.method == "POST":
            form = ProfileForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.save()
                return render(request, 'profile/start.html',{'rules':rules})
        elif request.method == "GET":
            try:
                profile = user.profile
                return render(request, 'profile/start.html',{'rules':rules})
            except Profile.DoesNotExist:
                form = ProfileForm(initial={'nick_name': user.username})
                return render(request, 'profile/profile.html', {'form': form})
    else:
        return redirect('home')


def leader_view(request):
    context = {'profiles': Profile.objects.all().order_by('-marks')}
    if request.user.is_authenticated:
        try:
            profile = request.user.profile
            if profile:
                if profile.current_question:
                    context['text'] = "Let's Continue"
                    context['has_started'] = True
                else:
                    context['text'] = "Let's Start"
                    context['has_started'] = False
        except Profile.DoesNotExist:
            context['text'] = "Let's Start"
            context['has_started'] = False
    else:
        context['text'] = "Let's Start"
        context['has_started'] = False
    return render(request, 'profile/lead.html', context)


def logout(request):
    log_me_out(request)
    return redirect('home')

csi_localhost/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

csi_localhost/templates/profile/lead.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE HTML>
<html>
<head>
  <title>Treasure Hunt</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
  <noscript>
    <link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}"/>
  </noscript>
</head>
<body class="is-preload">

  {%if request.user.is_authenticated%}
  <div class="signout" >
    <img onclick="show_side_bar(this)" src={{ request.user.socialaccount_set.all.0.get_avatar_url }}>
    
  </div>
  <div id="sidebar" class="sidebar">
    <a>{{request.user.profile.nick_name | title}}</a>
    <a href="{%url 'user_profile:redirect'%}">Rules</a>
    <a class="logout_button" href="{% url 'user_profile:logout'%}">Logout</a>
    
  </div>
  {%endif%}
<div id="wrapper" class="fade-in" onclick="show_side_bar(this)">

  <ul class="circles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>



  <!-- Header -->
  <header id="header">
    <a class="logo">Enigma</a>
  </header>

  <!-- Nav -->
  <nav id="nav">
    <ul class="links">
      <li><a href="{% url 'home' %}">Home</a></li>
      {% if has_started %}
        <li><a href="{% url 'game:quiz' %}">{{ text }}</a></li>
      {% else %}
      {%if request.user.is_authenticated%}
      <li><a href="{%url 'user_profile:redirect' %}" >Let's start</a></li>
      {%else%}
      <li><a href="{% provider_login_url 'google' %}" >Let's start</a></li>
      {%endif%}
      {% endif %}
      <li class="active"><a href="#">Leader board</a></li>
    </ul>
  </nav>

  <!-- Main -->
  <div id="main">

    <!-- Featured Post -->
    <article class="post featured">
      <header class="major">

        <h2>Table Toppers</h2>
      </header>
      <ol>
        {% for profile in profiles %}
          <li class="leader-r"><span
                  class="name"><b> {{ profile.nick_name | title}}</b> </span><span>{{ profile.marks }}</span></li>
        {% endfor %}
      </ol>


    </article>


  </div>

  <!-- Scripts -->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
  <script src="{% static 'assets/js/browser.min.js' %}"></script>
  <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
  <script src="{% static 'assets/js/util.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

csi_localhost/templates/profile/profile.html
{%load static%}


<!DOCTYPE HTML>
<html>
	<head>
		<title>Treasure Hunt</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
		<div id="wrapper" style="height:100vh;" class="fade-in">
			<ul class="circles">
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
		</ul>

			<form method="post" class="profile_form">
            {% csrf_token %}
			{{ form }}
			<div style="text-align:center; margin:20px">
				<button type="submit">Submit</button>
		</div>
          </form>

			</div>
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
			<script>
				document.getElementById('navPanelToggle').innerHTML= "";
			</script>

	</body>
</html>

csi_localhost/templates/profile/start.html
{%load static%}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Treasure Hunt</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		{%if request.user.is_authenticated%}
		<div class="signout" >
		  <img onclick="show_side_bar(this)" src={{ request.user.socialaccount_set.all.0.get_avatar_url }}>
		  
		</div>
		<div id="sidebar" class="sidebar">
		  <a>{{request.user.profile.nick_name | title}}</a>
		  <a href="{%url 'user_profile:redirect'%}">Rules</a>
		  <a class="logout_button" href="{% url 'user_profile:logout'%}">Logout</a>
		  
		</div>
		{%endif%}
	  <div id="wrapper" class="fade-in" onclick="show_side_bar(this)">
	  
		<ul class="circles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
	</ul>

					<div id="intro">
						<h1>Before you go!</h1>
						<p>	{%for rule in rules%}{{rule.rule | safe}}{%endfor%}</p>

						
							<a href="{%url 'game:quiz'%}" class="button icon solid  fas fa-play scrolly">Continue</a>
                        
                        
                    </div>
                    <!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li ><a href="{%url 'home' %}">Home</a></li>
							<li class="active"><a href="#" >Let's start</a></li>
							<li><a href="{%url 'user_profile:lead' %}">Leader board</a></li>
							</ul>
					</nav>

				

	





			</div>

		<!-- Scripts -->
		<script src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
		<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
		<script src="{% static 'assets/js/browser.min.js' %}"></script>
		<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
		<script src="{% static 'assets/js/util.js' %}"></script>
		<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>